receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    enable_open_metrics: true
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write

processors:
  batch:
    timeout: 1s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus, prometheusremotewrite]
#    logs:
#      receivers: [otlp]
#      exporters: [debug]
