global: 
  evaluation_interval: 1s
  scrape_interval: 1s
scrape_configs: 
  - job_name: 'otel-collector'
    static_configs: 
      - targets:
#          - otel-collector:8889
          - otel-collector:8888
